# Build configuration for code generation
targets:
  $default:
    builders:
      # Riverpod code generation
      riverpod_generator:
        options:
          # Generate code for @riverpod annotations
          enabled: true

      # Drift database code generation
      drift_dev:
        options:
          # Generate type-safe database code
          sql:
            dialect: sqlite
            options:
              version: "3.39"
          store_date_time_values_as_text: true
          generate_connect_constructor: true

      # Freezed for immutable models
      freezed:
        options:
          # Generate copyWith, ==, hashCode, toString
          union_factory: true
          union_value: true
          equal: true
          map: true
          copyWith: true
          to_json: true
          from_json: true

      # JSON serialization
      json_serializable:
        options:
          any_map: false
          checked: true
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          generic_argument_factories: true
          ignore_unannotated: false
          include_if_null: true

      # Reactive forms
      reactive_forms_generator:
        options:
          enabled: true
